export default [
  {
    name: "automatic",
    label: "Automatic",
    aliases: null,
    default_rho: -1,
    need_inner_model: false,
  },
  {
    name: "uniform",
    label: "Uniform",
    aliases: null,
    default_rho: -1,
    need_inner_model: true,
  },
  {
    name: "karras",
    label: "Karras",
    aliases: null,
    default_rho: 7,
    need_inner_model: false,
  },
  {
    name: "exponential",
    label: "Exponential",
    aliases: null,
    default_rho: -1,
    need_inner_model: false,
  },
  {
    name: "polyexponential",
    label: "Polyexponential",
    aliases: null,
    default_rho: 1,
    need_inner_model: false,
  },
  {
    name: "sgm_uniform",
    label: "SGM Uniform",
    aliases: ["SGMUniform"],
    default_rho: -1,
    need_inner_model: true,
  },
  {
    name: "kl_optimal",
    label: "KL Optimal",
    aliases: null,
    default_rho: -1,
    need_inner_model: false,
  },
  {
    name: "align_your_steps",
    label: "Align Your Steps",
    aliases: null,
    default_rho: -1,
    need_inner_model: false,
  },
  {
    name: "simple",
    label: "Simple",
    aliases: null,
    default_rho: -1,
    need_inner_model: true,
  },
  {
    name: "normal",
    label: "Normal",
    aliases: null,
    default_rho: -1,
    need_inner_model: true,
  },
  {
    name: "ddim",
    label: "DDIM",
    aliases: null,
    default_rho: -1,
    need_inner_model: true,
  },
  {
    name: "beta",
    label: "Beta",
    aliases: null,
    default_rho: -1,
    need_inner_model: true,
  },
] as const;
